package fr.projectdescartes.web;

import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import fr.projectdescartes.domain.Acteur;
import fr.projectdescartes.domain.ActeurRepository;
import fr.projectdescartes.domain.Film;

@Component
@Controller
@RequestMapping(path="/acteur")
public class ActeurController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private ActeurRepository acteurRepository;

	@GetMapping(path="/acteur") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String prenom,@RequestParam String image, @RequestParam Collection<Film> films) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		Acteur a = new Acteur();
	
		a.setNomActeur(name);
		a.setPrenomActeur(prenom);
		a.setPhotoActeur(image);
		a.setOeuvres(films);

		acteurRepository.save(a);
		
		return "Saved";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Acteur> getAllUsers() {
		// This returns a JSON or XML with the users
		return acteurRepository.findAll();
	}
	
}
