package fr.projectdescartes.web;

import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import fr.projectdescartes.domain.Acteur;
import fr.projectdescartes.repository.ActeurRepository;
import fr.projectdescartes.domain.Film;

@Component
@Controller
@RequestMapping(path="/acteurs")
public class ActeurController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private ActeurRepository acteurRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam(value="image", required=false) String image, @RequestParam(value="films", required=false) Collection<Film> films) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		Acteur a = new Acteur();
	
		a.setName(name);
		a.setPhotoActeur(image);
		a.setOeuvres(films);

		acteurRepository.save(a);
		
		return "Saved";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Acteur> getAllActeurs() {
		// This returns a JSON or XML with the users
		return acteurRepository.findAll(new Sort(Sort.Direction.ASC, "name"));
	}
	
	@RequestMapping(method= RequestMethod.PUT)  
	 public void putActeur(@RequestBody Acteur acteur) {
		System.out.println("modifierActeur : " + acteur);
	 }
	
}
